{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.plugin",
    "module": "plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12288,
          "sha512": "4d6e9f8487044948c6ee6d6d448746646cb64687643fce40df26b9f91f775a8291745fb726b1bd586b5cf9be0ede87db8e3c8cddf8ea1546ef662f66bb9bfe96",
          "sha256": "c039f24c9e056fd0fd34358cff291a7f80da8478bd5b55c45367a52d636dafa2",
          "sha1": "dfc7e55cbabed1a485aa79fd313db9ac0307b3e8",
          "md5": "add4cabd7aeb5d6efc3a1104617d48ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.1.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0.jar",
          "url": "plugin-1.0.0.jar",
          "size": 12288,
          "sha512": "4d6e9f8487044948c6ee6d6d448746646cb64687643fce40df26b9f91f775a8291745fb726b1bd586b5cf9be0ede87db8e3c8cddf8ea1546ef662f66bb9bfe96",
          "sha256": "c039f24c9e056fd0fd34358cff291a7f80da8478bd5b55c45367a52d636dafa2",
          "sha1": "dfc7e55cbabed1a485aa79fd313db9ac0307b3e8",
          "md5": "add4cabd7aeb5d6efc3a1104617d48ef"
        }
      ]
    }
  ]
}
